project:
  type: website
  preview:
    port: 8811
    browser: false

website:
  title: "rugved's stuff"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



